import type { Metadata } from "next";
import { Lexend as FontSans } from "next/font/google"
import { Header } from "@/components/layout/header";
import "./globals.css";

const lexend = FontSans({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const lexendGiga = FontSans({
  variable: "--font-lexend-giga",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${lexend.variable} ${lexendGiga.variable} antialiased`}
      >
        <Header />
        <main>
          {children}

        </main>
      </body>
    </html>
  );
}
